/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/luca/Documents/personal/projects/portfolio//public/models/sample.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/public/models/sample.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus001.geometry} material={materials['Material.002']} position={[0.027, 0.022, -0.02]} />
    </group>
  )
}

useGLTF.preload('/public/models/sample.glb')
